name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create release keystore
      run: |
        mkdir -p android/app
        keytool -genkey -v -keystore android/app/release.keystore -alias release -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=DiabetesQuiz, OU=Mobile, O=HealthApp, L=Seoul, C=KR"
    
    - name: Create gradle.properties for signing
      run: |
        echo "MYAPP_UPLOAD_STORE_FILE=release.keystore" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=release" >> android/gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=android" >> android/gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=android" >> android/gradle.properties
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Clean and build release APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleRelease -x lint
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
    
    - name: Upload AAB (if exists)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
