name: Build Android AAB

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Create keystore
      run: |
        keytool -genkey -v -keystore android/diabetes-quiz-key.keystore -alias diabetes-quiz -keyalg RSA -keysize 2048 -validity 10000 -storepass diabetes123 -keypass diabetes123 -dname "CN=Diabetes Quiz Team, OU=Mobile Development, O=Health Education, L=Seoul, C=KR"
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Build with Gradle
      run: |
        cd android
        ./gradlew clean
        ./gradlew bundleRelease
    
    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
